# Generated by Django 5.1.4 on 2024-12-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_partner_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Đang chờ', 'Đang chờ'), ('Đã xác nhận', 'Đã xác nhận'), ('Đã hoàn thành', 'Đã hoàn thành')], max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.AutoField(primary_key=True, serialize=False)),
                ('release_date', models.DateField()),
                ('status', models.CharField(choices=[('Chưa phát hành', 'Chưa phát hành'), ('Đang phát hành', 'Đang phát hành'), ('Đã phát hành', 'Đã phát hành')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Chưa hoàn thành', 'Chưa hoàn thành'), ('Đang dịch', 'Đang dịch'), ('Hoàn thành', 'Hoàn thành')], max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
                ('translated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
