# Generated by Django 5.1.4 on 2024-12-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movie_order_release_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
