# Generated by Django 5.1.4 on 2024-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Khai thác phim', 'Khai thác phim'), ('Dịch phim', 'Dịch phim'), ('Phát hành phim', 'Phát hành phim'), ('Quản lý', 'Quản lý'), ('Quản lý khách hàng', 'Quản lý khách hàng')], max_length=50),
        ),
    ]
