# Generated by Django 5.1.4 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='movie_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
