from django.urls import path
from . import views

urlpatterns = [
    path('', views.login),
    path('authorize', views.authorize),
    path('login/', views.login_view, name='login'),
    path('partners/', views.parteners_view, name='partners'),
    path('statics/', views.statics_view, name='statics'),
    path('orders/', views.orderpartner_view, name='view_order'),
    path('api/employees/', views.get_employee, name='get_employees'),
    path('api/employees/add/', views.add_employee, name='add_employee'),
    path('api/employees/edit/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('api/employees/delete/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    path('api/movies/', views.get_movies, name='get_movies'),
    path('api/movies/add/', views.add_movie, name='add_movie'),  
    path('api/movies/delete/<int:movie_id>/', views.delete_movie, name='delete_movie'),
    path('api/movies/edit/<int:movie_id>/', views.edit_movie, name='edit_movie'),
    path('api/translations/', views.get_translations, name='get_translations'),
    path('api/translations/add/', views.add_translation, name='add_translation'),
    path('api/translations/delete/<int:translation_id>/', views.delete_translation, name='delete_translation'),
    path('api/translations/edit/<int:translation_id>/', views.edit_translation, name='edit_translation'),
    path('api/releases', views.get_releases, name='get_releases'),  
    path('api/releases/edit/<int:release_id>/', views.edit_release, name='edit_release'),  
    path('api/releases/add/', views.add_release, name='add_release'),  
    path('api/releases/delete/', views.delete_release, name='delete_releases'), 
    path('api/partners/', views.get_partners, name='get_partners'),
    path('api/partners/add/', views.add_partner, name='add_partner'),
    path('api/partners/edit/<int:partner_id>/', views.edit_partner, name='edit_partner'),
    path('api/partners/delete/<int:partner_id>/', views.delete_partner, name='delete_partner'),
    path('api/partners/<int:partner_id>/', views.get_partner, name='get_partner'),
    path('api/orders/', views.get_orders, name='get_orders'),
    path('api/orders/add/', views.add_order, name='add_order'),
    path('api/orders/delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('api/orders/edit/<int:order_id>/', views.edit_order, name='edit_order'),
    
]